---
- hosts: websever
  tasks:
    - name: change permisiion
      shell: sudo chmod 777 /var/run/docker.sock
      
    - name: login to jfrog
      shell: docker login -u kamataryallu003@gmail.com -p yallaling.jfrog.io  
    
    - name: pull an image
      shell: docker pull yallaling.jfrog.io/docker/devops_practice:{{ BUILD_NUMBER }}

    #- name: remove container
     # shell: docker rm -f devops_practice
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 yallaling.jfrog.io/docker/devops_practice:{{ BUILD_NUMBER }}
 
   
